In [4]:
import numpy as np

data = np.loadtxt("C:\\Users\\student\\Documents\\movie data\\ratings.dat",
                 delimiter="::", dtype=np.int64)

In [6]:
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [7]:
data.shape

(1000209, 4)

In [8]:
mean_rating_total = data[:,2].mean()

In [9]:
mean_rating_total

3.5815644530293169

user_ids = np.unique(data[:,0])

In [14]:
user_ids = np.unique(data[:,0])
user_ids

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [11]:
uesr_ids

NameError: name 'uesr_ids' is not defined

In [17]:
mean_values=[]
for user_id in user_ids:
    data_for_user=data[data[:,0]==user_id,:]
    value = data_for_user[:,2].mean()
    mean_values.append([user_id,value])

In [20]:
mean_values[:5]

[[1, 4.1886792452830193],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.1904761904761907],
 [5, 3.1464646464646466]]

In [21]:
mean_array=np.array(mean_values, dtype=np.float32)
mean_array[:5]

array([[ 1.        ,  4.18867922],
       [ 2.        ,  3.7131784 ],
       [ 3.        ,  3.90196085],
       [ 4.        ,  4.19047642],
       [ 5.        ,  3.14646459]], dtype=float32)

In [22]:
mean_array.shape

(6040, 2)

In [23]:
np.savetxt("C:\\Users\\student\\Documents\\movie data\\ratingsResult.csv"
           , mean_array, fmt="%.1f",delimiter=",")