In [5]:
import numpy as np

names = np.array(["김철수", "이승호", "박철호"])
data = np.random.randn(7,4)

In [6]:
names

array(['김철수', '이승호', '박철호'], 
      dtype='<U3')

In [8]:
data

array([[-1.0492822 , -0.13833254, -1.89970661, -1.08012837],
       [-1.71100436, -0.44700007,  0.03544745, -0.29277474],
       [-0.90096416,  0.15821687, -1.63353438, -0.17820864],
       [-1.10366643,  0.3031949 , -0.17180198,  0.52570911],
       [-1.56845576, -2.7153499 , -0.17254334,  0.76256813],
       [-1.28506273, -0.59942932, -0.49532566, -2.15008891],
       [ 0.67012597,  0.4685395 ,  0.36352028, -0.07711242]])

In [9]:
x = np.random.randn(8)

In [10]:
y = np.random.randn(8)
x

array([ 0.91650181,  0.98729638, -0.97955889,  1.88879945,  1.28773615,
        1.52687262,  0.92917762,  0.74500037])

In [11]:
np.maximum(x,y)

array([ 0.91650181,  0.98729638, -0.0764594 ,  1.88879945,  1.28773615,
        1.52687262,  0.92917762,  0.74500037])

In [12]:
arr = np.random.randn(5,4)

In [13]:
arr

array([[-0.91365892,  0.28017877, -0.15625716,  2.1122553 ],
       [-0.07779372,  0.27662953, -1.41554771,  0.95943715],
       [-0.24880781,  1.29225291, -0.00863753,  0.72002531],
       [ 0.20149297,  1.40034986, -0.83844718,  1.10920504],
       [ 0.47040891, -1.33251989, -1.81886961,  1.57301402]])

In [14]:
arr.sum()

3.5847102577361012

In [15]:
arr.mean()

0.17923551288680506

In [16]:
arr.sum(axis=0)

array([-0.56835857,  1.91689118, -4.23775918,  6.47393683])

In [17]:
arr.sum(axis=1)

array([ 1.322518  , -0.25727475,  1.75483288,  1.87260069, -1.10796656])

In [18]:
np.sort(arr)

array([[-0.91365892, -0.15625716,  0.28017877,  2.1122553 ],
       [-1.41554771, -0.07779372,  0.27662953,  0.95943715],
       [-0.24880781, -0.00863753,  0.72002531,  1.29225291],
       [-0.83844718,  0.20149297,  1.10920504,  1.40034986],
       [-1.81886961, -1.33251989,  0.47040891,  1.57301402]])

In [19]:
np.sort(arr,axis=0)[::-1]

array([[ 0.47040891,  1.40034986, -0.00863753,  2.1122553 ],
       [ 0.20149297,  1.29225291, -0.15625716,  1.57301402],
       [-0.07779372,  0.28017877, -0.83844718,  1.10920504],
       [-0.24880781,  0.27662953, -1.41554771,  0.95943715],
       [-0.91365892, -1.33251989, -1.81886961,  0.72002531]])

In [24]:
names = np.array(["김철수", "이승호", "박철호", "박철호"])
ages = np.array([20,25,28, 20])
print(np.unique(names))
print(len(np.unique(names)))

['김철수' '박철호' '이승호']
3


In [25]:
print(np.unique(ages))

[20 25 28]
